#сборка платформы. Здесь используется два процессора
platform:
  - x86
  - x64
#среда разработки, указывается то, что необходимо для сборки проекта 
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#то, что запускается сразу после клонирования    
install:
  # Вывод версий для дебага
  - java -version
  - mvn --version
before_build: echo I'm starting building!
after_build: echo Build has finished
#запуск скрипта сборки проекта, если не берется по умолчанию MSBuild
build_script:
  - mvn --batch-mode -DskipTests package
#запуск собственного теста вместо автоматического  
test_script:
  - mvn --batch-mode test verify
#кэш сборки для сохранения файлов / папок между сборками  
cache:
- C:\Users\appveyor\.m2
